version: .{build}
os: Visual Studio 2017
init:
  - ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyy.M.d).$env:appveyor_build_number"
before_build:
- nuget restore src/Logazmic.sln
configuration:
  - Release
build:
  project: src/Logazmic.sln
  verbosity: minimal
after_build:
  - ps: squirrel/build-appveyor.ps1
artifacts:
  - path: squirrel/Releases/*
branches:
  only: 
    - master
skip_tags: true
deploy:
  tag: $(appveyor_build_version)
  release: Logazmic - $(appveyor_build_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: avB/QSAB0oqYutIGEeLkfdv9b3hJOhFv+RWVoL6916LEZcjVozeLkLTneC6OL9cl
  on:
    branch: master
cache:
  - src/packages
