image: Visual Studio 2022
  
init:
  - ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyy.M.d).$env:appveyor_build_number"
  
before_build:
  - ps: Install-Product dotnet "8.0.x"
 
configuration:
  - Release
  
build_script:
  - cmd: dotnet publish src\Logazmic\Logazmic.csproj -c Release -r win-x64
  - ps: squirrel/build-appveyor.ps1
  
artifacts:
  - path: squirrel/Releases/*
  
branches:
  only: 
    - master
    
skip_tags: true

deploy:
  tag: $(appveyor_build_version)
  release: Logazmic - $(appveyor_build_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: avB/QSAB0oqYutIGEeLkfdv9b3hJOhFv+RWVoL6916LEZcjVozeLkLTneC6OL9cl
  on:
    branch: master
